[DRAFT] Feature/base64 speedup
rungalileo/dataquality pull request #491
Opened 2023-01-18 20:28 UTC by rfriel

> **Please do not create a pull request without creating an issue first.**
>
> Changes need to be discussed before proceeding, pull requests submitted without linked issues may be rejected.
>
> Please provide enough information so that others can review your pull request. You can skip this if you're fixing a typo – it happens.

* [ ] I have added tests to `tests` to cover my changes.
* [ ] I have updated `docs/`, if necessary.
* [ ] I have updated the `README.md`, if necessary.

***What existing issue does this pull request close?***

Put `closes #issue-number` in this pull request's description to auto-close the issue that this fixes.

***How are these changes tested?***

This pull request includes automated tests for the code it touches and those tests are described below. If no tests are included, reasons why must be provided below.

These changes are tested with [...]

***Demonstration***

Demonstrate your contribution.

For example, what are the exact commands you ran and their output, related screenshots, screen-recordings, test runs, anything that can showcase.

***Provide additional context.***

Provide as much relevant context as you like.

2023-01-18 21:11 UTC, anthonycorletti approved these changes

2023-01-18 21:31 UTC, Ben-Epstein requested changes
nice! Can we add a quick test for these helpers?

2023-01-18 22:47 UTC, rfriel commented
> nice! Can we add a quick test for these helpers?

I added `test_base64_image_logging` -- is that the kind of thing you wanted?  It's a bit complicated... I wasn't sure how to write a simple test given that we have to deal with images and files here.

I wanted to turn the part that makes a synthetic image dataset into a shared utility, but it might be tricky because of the tempfile stuff, so I just added a TODO.

2023-01-20 16:56 UTC, Ben-Epstein approved these changes
this is great!

2023-01-20 17:07 UTC, elboy3 approved these changes

2023-01-23 18:45 UTC, merged