Feature/structured classification WIP
rungalileo/dataquality pull request #493
Opened 2023-01-23 19:05 UTC by elboy3

> **Please do not create a pull request without creating an issue first.**
>
> Changes need to be discussed before proceeding, pull requests submitted without linked issues may be rejected.
>
> Please provide enough information so that others can review your pull request. You can skip this if you're fixing a typo – it happens.

* [ ] I have added tests to `tests` to cover my changes.
* [ ] I have updated `docs/`, if necessary.
* [ ] I have updated the `README.md`, if necessary.

***What existing issue does this pull request close?***

Put `closes #issue-number` in this pull request's description to auto-close the issue that this fixes.

***How are these changes tested?***

This pull request includes automated tests for the code it touches and those tests are described below. If no tests are included, reasons why must be provided below.

These changes are tested with [...]

***Demonstration***

Demonstrate your contribution.

For example, what are the exact commands you ran and their output, related screenshots, screen-recordings, test runs, anything that can showcase.

***Provide additional context.***

Provide as much relevant context as you like.

2023-01-30 17:01 UTC, Ben-Epstein commented on dataquality/core/log.py
> +        )
this seems all about NLP data. I'd keep "Invalid example" but update this to a tabular example, and change it to `dq.log_structured_samples`

2023-01-30 17:03 UTC, Ben-Epstein commented on dataquality/core/log.py
> +    probs: np.ndarray,
some people _may_ have the `probs` as a column in the pandas df.. Not necessarily, but it might be worth considering supporting that now or in the future, instead of requiring a separate numpy array.

You can have a column with lists in a pandas df, its just a little odd

2023-01-30 17:04 UTC, Ben-Epstein commented on dataquality/core/log.py
> +        dataset=dataset,
do you want to validate that the dataset is a pandas df?

2023-01-30 17:06 UTC, Ben-Epstein commented on dataquality/loggers/data_logger/structured_classification.py
> +            - Inference name is set if split is inference (TODO)
shouldnt the base logger validate this already?

2023-01-30 17:06 UTC, Ben-Epstein commented on dataquality/loggers/data_logger/structured_classification.py
> +        assert len(self.feature_names) == len(self.X[0])
I'd add an error message for each of these that is user friendly

2023-01-30 17:08 UTC, Ben-Epstein commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.y = dataset[label].values
idk if this is true for pandas, but `.values` may be risky. Pandas is built on pyarrow, so it's possible you might get back a pyarrow ListArray, or a numpy array. If that's the case, I'd be explicit and use `tolist` or `to_numpy` (or whatever the api is for pandas)

2023-01-30 17:10 UTC, Ben-Epstein commented on dataquality/loggers/data_logger/structured_classification.py
> +            data.update(inference_name=self.inference_name)
does this not need to be `data.update(inference_name=[self.inference_name]*num_samples)` like split?

2023-01-30 17:16 UTC, Ben-Epstein commented on dataquality/loggers/data_logger/structured_classification.py
> +            desc="Uploading Data",
You have an outer tqdm bar in `upload` with the same message.

I would
1. make the description `Uploading {split} data` since you know the split at this point
2. Make this bar disappear after upload (we have that in other places, I think the api is like `leave=False` or something

OR you might just not need this inner tqdm bar at all. You are uploading relatively small amounts of data (i presume), and we have the upload progress bar in `create_project_run_object_from_df` - so there may be enough live user feedback to not warrent this inner progress bar

2023-01-30 17:18 UTC, Ben-Epstein commented on tests/conftest.py
> +        dataquality.get_data_logger(task_type).logger_config.reset()
i see why you did this, but for continuity sake I feel like you should create a `StructuredDataModelLogger` that inherits from `BaseModelLogger` and just doens't do anything...

2023-01-30 17:23 UTC, Ben-Epstein reviewed
This all looks great. 

You implemented this following the paradigms of the other tasks which is nice for consistency and (i think) should make this scalable to really big datasets in theory.

The one thing though, is that because in structured we fundamentally log all the data at once, I'm not sure the complexity is necessarily worth it? I'll definitely leave that up to you, but consider the flow of data currently:

1. Get pandas dataframe from user
2. Parse it into our `DataLogger` class 
3. Validate the data
4. Parse that data into a dictionary (which was essentially the same as the pandas df `.to_records()`)
5. Write that to disk as an hdf5 file
6. Read it from disk into a vaex dataframe 
7. Upload that vaex df into 2 parts (probs, data)

It's a bit redundant in the passing around of the data. For example, you are validating that all of the features have the same length, but since it started in a pandas dataframe you don't actually need to do that.

A potentially simpler flow would be to simply
1. Get the pandas df from the user
2. Validate the pandas df (not even sure really what needs to be validated)
3. Create a vaex df in-memory `df = vaex.from_pandas_df(pdf)`
4. Upload that vaex df into 2 parts (probs, data)

You certainly don't need to do that, but (unless I'm missing something), that would accomplish the same thing

2023-01-31 21:47 UTC, elboy3 commented on dataquality/loggers/model_logger/base_model_logger.py
moved to base logger

2023-02-01 00:12 UTC, asanyal commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.probs = self.model.predict_proba(input_data)
Quick note to measure the perf of this line of code. In general would be great to do some basic tests and measure the latency of `predict_proba` + how it varies with dataset sizes.

2023-02-01 00:15 UTC, asanyal commented on dataquality/loggers/data_logger/structured_classification.py
> +        df = vaex.from_pandas(self.dataset)
Just for my knowledge -- do we have a sense of how expensive these dataframe conversions calls are? My guess would be it's cheap, given it's not copying any data over, but want to confirm this.

2023-02-01 00:24 UTC, franz101 commented on dataquality/core/log.py
> +import xgboost as xgb
Lazy import?

2023-02-01 00:25 UTC, franz101 commented on dataquality/core/log.py
> +    .. code-block:: python
love the code block :)

2023-02-01 00:27 UTC, franz101 commented on dataquality/core/log.py
> +    model: xgb.XGBClassifier,
in some cases a str can do the job.
def func2(self, some_param: 'Main'):

2023-02-01 00:31 UTC, franz101 commented on dataquality/core/log.py
> +    model: xgb.XGBClassifier,
A couple of questions:
- Why would we pass in a xgboost classifier?

2023-02-01 00:34 UTC, franz101 commented on dataquality/loggers/base_logger.py
> +        return f"{BaseGalileoLogger.LOG_FILE_DIR}/{self.proj_run}"
👍

2023-02-01 00:35 UTC, franz101 commented on dataquality/loggers/base_logger.py
>          return str(split)
str(str())?

2023-02-01 00:36 UTC, franz101 commented on dataquality/loggers/base_logger.py
> +            split = f"{split}/{self.inference_name}"
for complex paths I can recommend the Pathlib

2023-02-01 00:38 UTC, franz101 commented on dataquality/loggers/base_logger.py
> +                    "or set it before logging. Use `dataquality.set_split` to set "
Some syntactic sugar:
```python
if self.split == Split.inference and not self.inference_name:
    self.inference_name = self.logger_config.cur_inference_name or raise GalileoException(
        "For inference split, either log an inference name "
        "or set it with `dataquality.set_split`. Current inference name is not set."
    )
```

2023-02-01 00:39 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +class StructuredClassificationDataLogger(BaseGalileoDataLogger):
General question, does StructuredClassificationDataLogger always need a model? If not would XGB as subset?

2023-02-01 00:40 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.probs = self.model.predict_proba(input_data)
@rfriel this could be a good place to run a few further experiments and confirm

2023-02-01 00:40 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +        df = vaex.from_pandas(self.dataset)
Extremely quick with vaex. Subsecond even on large datasets

2023-02-01 00:41 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +            model if model is not None else xgb.XGBClassifier()
or is your friend:
model or xgb.XGBClassifier()

2023-02-01 00:46 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +
sadly the same simplification doesn't work here:
`The truth value of an empty array is ambiguous`

2023-02-01 01:04 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +
Make parameter X np.array([]) by default?

2023-02-01 01:04 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +    def create_dataset_from_samples(
create_df_from_samples

2023-02-01 01:06 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +        dataset: pd.DataFrame,
curios about dataframe = dataset.
no lists/numpy arrays here?

2023-02-01 01:07 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +        """Sets the probs attribute for the class
what is the probs attribute?

2023-02-01 01:08 UTC, franz101 commented on dataquality/loggers/data_logger/structured_classification.py
> +        Note that unlike unstructured data, we don't batch data here, we write
why is the difference? I actually like this for structured data as well. otherwise init needs to be called all the time.

2023-02-01 01:19 UTC, franz101 commented on dataquality/loggers/model_logger/structured_classification.py
> +    # NOTE: Structured Classification doesn't require a model logger
because the model is not logging each time?

2023-02-01 01:23 UTC, franz101 reviewed
a couple of questions before I approve:
```why not dq.log_dataset(data)
and dq.log_model(model)```
and are we sure xgboost is not another requirement when we import from the core module?

🙏

2023-02-01 01:23 UTC, elboy3 commented on dataquality/core/log.py
> +import xgboost as xgb
why?

2023-02-01 01:25 UTC, elboy3 commented on dataquality/core/log.py
> +    model: xgb.XGBClassifier,
The user needs to log their model for structured data. This will allow us to calculate things like dep, feature importance, etc.

2023-02-01 01:25 UTC, elboy3 commented on dataquality/core/log.py
> +import xgboost as xgb
What do you think about the follpwing instead of lazy import 

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from xgboost import XGBClassifier
```

2023-02-01 01:26 UTC, elboy3 commented on dataquality/loggers/base_logger.py
>          return str(split)
🤷 this is just how it was already. i can remove

2023-02-01 01:26 UTC, elboy3 commented on dataquality/loggers/base_logger.py
> +                    "or set it before logging. Use `dataquality.set_split` to set "
😋

2023-02-01 01:27 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +
i think setting default to none is better, since the default param in python i mutable. but will do your suggestion for model above!

2023-02-01 01:28 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +        """Sets the probs attribute for the class
what do you mean?

2023-02-01 01:29 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +        Note that unlike unstructured data, we don't batch data here, we write
init only needs to be called once if I'm thinking about it right! 

basically with unstructured data we would have to batch upload because 1) epochs and 2) their texts may not fit into memory.

We don't have epochs or memory concerns (for now) in structured data

2023-02-01 01:30 UTC, elboy3 commented on dataquality/loggers/model_logger/structured_classification.py
> +    # NOTE: Structured Classification doesn't require a model logger
model outputs are not logged at all :) 

we get the model prob outputs from their model which is already logged

2023-02-01 01:31 UTC, elboy3 commented
@franz101 great review! I think it's better to just do one log `log_structured` than have them do 2 back to back logs. WDYT?

2023-02-01 01:34 UTC, elboy3 commented on dataquality/loggers/base_logger.py
> +                    "or set it before logging. Use `dataquality.set_split` to set "
wait. this doesn't work :( 

```
>>> a = 5
>>> b = ""
>>> c = a or raise Exception("yoo")
  File "<stdin>", line 1
    c = a or raise Exception("yoo")
             ^
SyntaxError: invalid syntax
```

2023-02-01 09:13 UTC, franz101 commented on dataquality/core/log.py
> +import xgboost as xgb
That's cool, i didn't know it existed

2023-02-01 23:56 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.probs = self.model.predict_proba(input_data)
I've done some experiments.  Briefly, yes, we can assume predict_proba is very fast (under 1 second for reasonable inputs).

In particular, for reasonably sized datasets and models, running `predict_proba` on the training data takes less than 1% as much time as it took to `fit` the model on the same data.

So if the user has the patience to fit the model, we're not adding much overhead on top of that.

2023-02-02 00:35 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.dataset.rename(columns={label: "gold"}, inplace=True)
Will this modify the dataframe the user passes as `dataset`?

That seems potentially confusing.

Also, if something fails in `log()`, and we call this function again to re-try, it will now fail because there's no column with the original label name.

2023-02-02 00:37 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +        label: Optional[str],
We need label to not be None.

2023-02-02 00:40 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +    def log_samples(
It would be nice if this called `log_structured_dataset`, to avoid having two code paths that can diverge.  Like

```python
        self.model = model
        self.split = split
        self.inference_name = inference_name
        self.dataset = self.create_dataset_from_samples(X, y, feature_names)
        self.log_structured_dataset(
                model=self.model, 
                dataset=self.dataset, 
                label="gold",
                split=self.split,
                inference_name=self.inference_name,
        )
```

2023-02-02 00:47 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +        input_data = self.dataset.copy()
I don't think the copy is necessary.  `input_data.drop` on the next line isn't inplace, it returns a modified copy.

2023-02-02 00:54 UTC, rfriel commented on tests/loggers/conftest.py
> +    model = xgb.XGBClassifier(objective="multi:softprob", random_state=42)
FYI, `XGBClassifier` will automatically set `objective="multi:softprob"` if passed multiclass data.

2023-02-02 01:39 UTC, rfriel reviewed
Left some comments.  Mostly looks great!

Most comments were nits.  The important things are

- We could have more intuitive names for the user-facing functions
- The dataframe-logging function should have separate X and y arguments, like the numpy-logging one does

2023-02-02 01:39 UTC, rfriel commented on dataquality/core/log.py
> +    data_logger.log_structured_dataset(
We should probably also check whether the model has been fitted.  Something like

```
from sklearn.utils.validation import check_is_fitted
    [...]
    assert check_is_fitted(
        model
    ), "This model has not been fitted.  Fit the model before calling log_structured_dataset."
```

2023-02-02 01:39 UTC, rfriel commented on dataquality/__init__.py
> +    log_structured_dataset,
These names are potentially confusing -- they sound like they're just about the data, but they're really about the data together with a fitted model.

We're treat it as "data logging" internally, but that's an implementation detail.

IMO the user-facing name should express "this is the function that logs everything to Galileo, if you're doing structured classification."

The "samples" vs. "dataset" nomenclature is also confusing.  Makes it sounds like if you're logging "samples," you're only logging a subset of the data... or something.

So maybe 

- `log_structured_samples` --> `log_structured_classification_from_arrays`
- `log_structured_dataset` --> `log_structured_classification_from_df`

2023-02-02 01:39 UTC, rfriel commented on dataquality/core/log.py
> +    dataset: pd.DataFrame,
IMO, we should accept separate `X` and `y` arrays in this function, where `X` is a dataframe.

`XGBClassifier.fit(X, y)` can accept a pandas dataframe as `X`.  If you have a dataframe already, this is the most convenient way to fit the model.

However, you can't do `XGBClassifier.fit(df)` where df contains both X and y.

At the point where the user calls our logger, they have just done 

```python
# X: pd.DataFrame or np.ndarray
# y: np.ndarray
model.fit(X, y)
```

We can assume they have these two objects, X and y.  They might not have a combined dataframe with both X and y, and if so, it's awkward to ask them to create it.

This would also mean we don't need to ask the user for the (arbitrary) name that they assigned to the label in the combined df (the `label` arg).

2023-02-02 01:39 UTC, rfriel commented on dataquality/core/log.py
> +        dq.log_dataset(model, X, feature_names, y=y, split="training")
Shouldn't this be `dq.log_structured_samples`?  And below on line 179

2023-02-02 01:39 UTC, rfriel commented on dataquality/core/log.py
> +        dq.log_dataset(model, dataset, label="label", split="training")
Shouldn't this be `dq.log_structured_dataset`?  And below on line 248

2023-02-02 02:03 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +        self.dataset.rename(columns={label: "gold"}, inplace=True)
As is now it will, good call. Will need to make sure to copy any pandas DF that we want to modify

2023-02-02 23:45 UTC, rfriel requested changes
Much cleaner/simpler this way!

Left some comments.

2023-02-02 23:45 UTC, rfriel commented on dataquality/__init__.py
> +    "log",
The user-facing name should be something that won't seem relevant if you're doing deep learning.

Possibilities:

- `dq.log_structured`
- `dq.log_xgboost`
  - if/when we make it explicit that we support general sklearn models, could be replaced with `dq.log_sklearn`
- or maybe create a new module under `dq`, like `dq.structured.log` or`dq.xgboost.log`

I much prefer `log_xgboost` to `log_structured`, since it's not obvious from context what "structured" means.

The last one seems like a good direction long-term when we have lots of modalities, to prevent `dq` from having a million log_whatever functions.  But maybe not in this PR, up to you.

2023-02-02 23:45 UTC, rfriel commented on dataquality/core/log.py
> +        df = pd.DataFrame(data.data, columns=data.feature_names)
I would suggest writing this example like this:

```python
         X, y = load_wine(as_frame=True, return_X_y=True)

        model = xgb.XGBClassifier()
        model.fit(X, y)

        dq.log(model, X=df, y=y, split="training")
```

This is how I've been using the sklearn loaders in my experiments.

2023-02-02 23:45 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +            self.X = (
This is inside `if isinstance(self.X, np.ndarray):`, so we can remove the if/else part.

2023-02-02 23:45 UTC, rfriel commented on dataquality/loggers/data_logger/structured_classification.py
> +            else self.X.index.to_numpy()
Pandas dataframes can have duplicates in their indices, and this often arises in practice.  But we can't handle duplicate IDs.

So we should either 

- check if the index has duplicates (eg `self X.index.duplicated().any()`), and if it does, fall back to `np.arange(len(self.X))` or something
- Or, always use `np.arange(len(self.X))` instead of the index if there's no ID column.

It's possible that the user has put meaningful, unique IDs in their dataframe index, and if so I guess we might want to preserve those...

But this behavior isn't documented, which means it's really bad if we fail because of it.  The user doesn't know we're doing this, and we're not telling them that their df has to have a unique index.

2023-02-03 15:50 UTC, elboy3 commented on dataquality/loggers/data_logger/structured_classification.py
> +            else self.X.index.to_numpy()
id is used on our end to match columns in the data df and the probs df in the VaexService. So the ids don't really matter and the user will never see them. I think we should just go with `np.arange(len(self.X))`

2023-02-03 17:42 UTC, elboy3 commented on dataquality/__init__.py
> +    "log",
I'm going to keep it simple with `log_xgboost` for now, but i definitely agree the future direction. 

as we add new models, requirements, modalities to structured i think the naming conventions will be more clear to us, and it will be easy to change

2023-02-03 18:22 UTC, rfriel approved these changes
💯

2023-02-03 18:23 UTC, merged