Improve YOLO test speed
rungalileo/dataquality pull request #603
Opened 2023-05-16 00:53 UTC by franz101

Instead of training on coco128 we create a custom dataset and we only have 4 samples

2023-05-18 19:55 UTC, franz101 commented on dataquality/utils/ultralytics.py
@bogdan-galileo have a look here regarding the relative path

2023-05-19 18:02 UTC, bogdan-galileo commented on tests/integrations/ultralytics/test_cv_yolo.py
> +        # less than 5 samples PCA is 5,5 otherwise 100
it's more: less than 100 samples PCA is (n_samples, n_samples) otherwise (n_samples, 100)

2023-05-19 18:02 UTC, bogdan-galileo commented on dataquality/loggers/model_logger/object_detection.py
> +        print("image_ids.shape")
do you want to remove all the `print` ?

2023-05-19 18:05 UTC, bogdan-galileo commented on dataquality/loggers/model_logger/object_detection.py
> +        embs = gold_emb_arrays
can you add a comment explaining the logic ? Also, do we want to only do 1 if ? Should they either all pass or all fail ?

2023-05-19 18:43 UTC, Ben-Epstein requested changes
I'm not sure what exactly is happening in this PR exactly. Why are we changing so much about the Object Detection logger?

Also seeing a lot of print statements

2023-05-19 20:58 UTC, franz101 commented
@Ben-Epstein removed the print statements. essentially the model logger was failing if there were no predictions for the batch at all. therefore we need to fallback to empty arrays and make sure the shapes are equal. remove the print statements

2023-05-19 21:08 UTC, Ben-Epstein commented on tests/integrations/ultralytics/test_cv_yolo.py
> +        print(tmp_cfg_path)
```suggestion
```

2023-05-30 15:26 UTC, bogdan-galileo commented on dataquality/loggers/model_logger/object_detection.py
> +        # prob = np.concatenate([pred_prob_arrays, np.zeros(gold_prob_shape)])
want to cleanup the older `np.concat` ?

2023-05-30 15:28 UTC, bogdan-galileo approved these changes
Tested with our publicly facing notebook and a YAML file without the key `path` https://console.dev.rungalileo.io/insights?projectId=543aedcf-2eb5-422c-95f0-c2e641ef15da&runId=7dc85dce-c64d-480c-90df-8546c7623c55&insightsTab=metrics&taskType=5. Looks good to me!

2023-05-30 19:46 UTC, Ben-Epstein commented on dataquality/loggers/model_logger/object_detection.py
> +        # prob = np.concatenate([pred_prob_arrays, np.zeros(gold_prob_shape)])
```suggestion
        # prob = np.concatenate([pred_prob_arrays, np.zeros(gold_prob_shape)])
```

2023-05-30 19:47 UTC, Ben-Epstein approved these changes

2023-05-31 04:32 UTC, merged