chore: Add prompt eval to task type
rungalileo/dataquality pull request #629
Opened 2023-05-23 16:49 UTC by setu4993

Just adding the new task type to keep `dataquality` aligned.

2023-05-23 19:42 UTC, elboy3 commented on dataquality/schemas/task_type.py
> +        """Tasks that are valid for dataquality."""
if we do it this way, let's add more to this docstring to explain the context of what "valid" means and why prompt evaluation isn't "valid"

2023-05-23 19:43 UTC, elboy3 commented on dataquality/schemas/task_type.py
> +            if task_type not in [TaskType.prompt_evaluation]
i would maybe suggest adding a new static method something like `get_logger_task_types` or `get_dq_task_types` or something along those lines that excludes prompt eval instead of hijacking this fn

2023-05-23 19:44 UTC, elboy3 requested changes
left a few thoughts

2023-05-23 19:54 UTC, setu4993 commented on dataquality/schemas/task_type.py
> +    def get_valid_tasks() -> List["TaskType"]:
I thought about it but it doesn't have any downstream impact, which is why I felt comfortable changing it. Curious why you think we should match the signature?

2023-05-24 18:48 UTC, elboy3 commented on dataquality/schemas/task_type.py
> +    def get_valid_tasks() -> List["TaskType"]:
ahh cool, i didn't know the enum in an f string would work, but since it does, i'm cool with it

2023-05-24 20:19 UTC, elboy3 approved these changes

2023-05-25 16:17 UTC, merged