Feature/text generation seq2seq
rungalileo/dataquality pull request #734
Opened 2023-08-09 14:16 UTC by elboy3

> **Please do not create a pull request without creating an issue first.**
>
> Changes need to be discussed before proceeding, pull requests submitted without linked issues may be rejected.
>
> Please provide enough information so that others can review your pull request. You can skip this if you're fixing a typo – it happens.

* [ ] I have added tests to `tests` to cover my changes.
* [ ] I have updated `docs/`, if necessary.
* [ ] I have updated the `README.md`, if necessary.

***What existing issue does this pull request close?***

Put `closes #issue-number` in this pull request's description to auto-close the issue that this fixes.

***How are these changes tested?***

This pull request includes automated tests for the code it touches and those tests are described below. If no tests are included, reasons why must be provided below.

These changes are tested with [...]

***Demonstration***

Demonstrate your contribution.

For example, what are the exact commands you ran and their output, related screenshots, screen-recordings, test runs, anything that can showcase.

***Provide additional context.***

Provide as much relevant context as you like.

2023-08-09 14:16 UTC, elboy3 commented
Not even close to being ready to be reviewed

2023-08-09 14:27 UTC, elboy3 commented on dataquality/utils/helpers.py
> +    return task
moved from `dataquality/core/log.py`

2023-08-09 19:48 UTC, elboy3 commented on dataquality/loggers/data_logger/seq2seq.py
> +        model.eval()
torch.no_grad

2023-08-09 19:48 UTC, elboy3 commented on dataquality/loggers/data_logger/seq2seq.py
> +        :param epoch_or_inf: The epoch or inference name we are logging for
update :)

2023-08-09 19:49 UTC, elboy3 commented on dataquality/loggers/data_logger/base_data_logger.py
> +        # and run the text through the tokenizer and model
remove

2023-08-10 22:32 UTC, Ben-Epstein requested changes
tests??!?!?!?

2023-08-10 22:58 UTC, setu4993 reviewed
Left a few questions below, let's chat more tomorrow.

2023-08-10 22:58 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            )
I'd honestly expect this to be a fairly expensive (time + compute) process that scales linearly with the dataset.

Also, if we're not hooking up with the user's own generate fn, we'll have a different output than what maybe they're looking at (temperature, num beams, etc.).

2023-08-10 22:58 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            generated_tokens = generation_respone.sequences[0, 1:]
Why? I think we'd want it because that's what tells the model to start generating...

2023-08-10 22:58 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
Curious about how this impacts our calculations? Do we also drop it when calculating DEP?

2023-08-10 22:58 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +    def generate_output(text: pa.array) -> np.ndarray:
How is text `pa.array` 🤔? Maybe this warrants naming it as something different since it's tokenized input?

2023-08-10 22:58 UTC, setu4993 commented on dataquality/schemas/seq2seq.py
> +            df.rename(cls.text.value, cls.input.value)
Neat (and fallible) that `vaex` renames inplace.

2023-08-10 22:58 UTC, setu4993 commented on dataquality/integrations/seq2seq/hf.py
> +        model, PreTrainedModel
Do we need to limit to models that can generate?

2023-08-10 22:58 UTC, setu4993 commented on dataquality/integrations/seq2seq/hf.py
> +    assert model.can_generate(), "model must contain a `generate` method for seq2seq"
Ah, never mind :).

2023-08-11 15:13 UTC, jonathangomesselman commented on dataquality/integrations/seq2seq/hf.py
> +    if generate_training_data:
We should maybe put a warning / flag here that clearly notifies the user `Hey you're choosing to generate on the Training Data which may take quite a bit of time!`

2023-08-11 15:16 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +    def generate_output(text: pa.array) -> np.ndarray:
I think I agree there. In other situations we have added `tokenized` to the name?

2023-08-11 15:17 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +    def generate_output(text: pa.array) -> np.ndarray:
@setu4993 I think it is a `pa.array[string]` - i.e. a list of text strings. Maybe this would be better called `texts`

2023-08-11 15:21 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            )
Yes this will definitely be an expensive process. I think that is why we should especially warn users when they indicate that they want to generate over the training data.

2023-08-11 15:33 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            )
Super valid point about the generate function. Here are some of my thoughts on it based on some research into how different repos use hf's generate + how I have been using it.

Essentially, it seems like a pretty common generation pattern is to just rely on hf's `generate` function, which is built in to all generative models. Pretty classically (and great for us), hf has made the generation process very standardized and simple, abstracting much of the work away from the user. The key lies in the `generation_config`, which allows you to specify parameters such as `temperature`, `top_k`, `top_p`, ... even things like `num_beams`.

The `num_beams` is a great point though. My thinking was that for our first pass at this we should skip support for beam based generation. We can certainly handle this down the road, it just adds a small bit of complexity in how the `generation_response` is formatted. I think generally we would just have to have a switch case to process `generation_response` differently based on its returned `type` (which changes based on if you use `beam_search`).

How does this sound @setu4993? There is definitely then the possibility that they are using something completely different, which hf does not support. My hope is this will not happen often and if it does we can cross that bridge when it does?

2023-08-11 15:40 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            generated_tokens = generation_respone.sequences[0, 1:]
We definitely want it when we pass the `input_ids` to the model, but when we process the generated response I think we would want to remove it. As a user I wouldn't expect to see the `pad` token - as it is somewhat implied as the start of the generation.

2023-08-11 17:32 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
My thinking was yes! This was something I was not 100% sure about, but generally I have seen people remove special tokens when they for example visualize generated output. 

In general, my thinking was that we would not show probs / text for the <eos> token. However, it can be something valuable, especially if you are fine-tuning your model with the expectation that it will stop generating in specific situations and this is not happening. So visualizing the model's log probs over the <eos> token could be interesting - though I have not seen this really done.

2023-08-11 17:34 UTC, jonathangomesselman commented on dataquality/loggers/data_logger/seq2seq.py
> +        model.eval()
Yes! You can also add this fun little decorator `@torch.no_grad()`. I have seen it used extensively in the hf repo to avoid endlessly having to do `with torch.no_gra():`

2023-08-11 17:35 UTC, jonathangomesselman commented
@setu4993 - Added responses to your questions. Happy to chat more through some of the design choices. Thanks for the help here!

2023-08-14 16:18 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            )
Generation is expensive regardless of the data split it is running on, which is why we shouldn't regenerate (as we're doing here) but use what the user generates as a part of their training / validation / evaluation loop.

> Essentially, it seems like a pretty common generation pattern is to just rely on hf's `generate` function, which is built in to all generative models. Pretty classically (and great for us), hf has made the generation process very standardized and simple, abstracting much of the work away from the user. The key lies in the `generation_config`, which allows you to specify parameters such as `temperature`, `top_k`, `top_p`, ... even things like `num_beams`.

Yeah, I know :). I've been using it for ~4 years and it's pretty neat to have a single API to use!

> The `num_beams` is a great point though. My thinking was that for our first pass at this we should skip support for beam based generation. We can certainly handle this down the road, it just adds a small bit of complexity in how the `generation_response` is formatted. I think generally we would just have to have a switch case to process `generation_response` differently based on its returned `type` (which changes based on if you use `beam_search`).

I don't really follow how the type changes if we use beam search 🤔. From what I remember and ([just confirmed from the docs](https://huggingface.co/docs/transformers/v4.31.0/en/generation_strategies#beamsearch-decoding)) the dtype remains the same: `str` regardless of beam search (`list` is because it's a "batch" being decoded), since beam search is an internal decoding detail and not surfaced to the user as multiple responses.

> How does this sound @setu4993? There is definitely then the possibility that they are using something completely different, which hf does not support. My hope is this will not happen often and if it does we can cross that bridge when it does?

My biggest concern is us _duplicating_ the generation step, which I am certain we shouldn't do. This is where we get mismatches between what the user is doing vs. what we are doing and can lead users to lose trust in the product because, well, we aren't showing them the outputs they see.

If this were text classification, this would be equivalent to us showing different classes than the actual prediction. That's the impact of changing _anything_ about the generation strategy.

2023-08-14 16:18 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            generated_tokens = generation_respone.sequences[0, 1:]
Yea, but `tokenizer.decode` would simply take it out :).

We shouldn't need to do special handling.

2023-08-14 16:18 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
> generally I have seen people remove special tokens when they for example visualize generated output.

Yes, but it doesn't need to be handled separately outside using the defaults (see ^ comment).

If we want to drop something, let's use a mask instead of relying on slicing.

2023-08-14 16:18 UTC, setu4993 commented on dataquality/schemas/seq2seq.py
> +            df.rename(cls.text.value, cls.input.value)
@elboy3 : `pandas`, `pyarrow`, etc. do not perform operations like rename on an existing DF but on a copy. That prevents inadvertent issues from occurring.

When I originally read the removed line, what I got was: We were following the `pandas` pattern and creating a new DF with renamed columns. It being modified here led me to the docs, which helped me realize the OP :).

2023-08-14 17:45 UTC, elboy3 commented on dataquality/utils/seq2seq.py
> +            )
@setu4993 so the main requested change here is that instead of doing a final pass over the data to log the model's post training "generated output" for the split, we should log the generated output at each epoch and just use the output for the last epoch as generated ?


what outputs are different btwn what we show them and what they see (what do you mean by "outputs they" see by the way?)

2023-08-14 17:47 UTC, elboy3 commented on dataquality/utils/seq2seq.py
> +    def generate_output(text: pa.array) -> np.ndarray:
Yup, I think the typing should actually be `pa.StringArray`, will fix

2023-08-14 17:50 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            )
The main requested change is that instead of us _generating_ the output, we should hook into the user's process for generating those outputs.

By "outputs they see" I mean the outputs the user generates as a part of their validation loop.

2023-08-14 18:16 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            generated_tokens = generation_respone.sequences[0, 1:]
Good point. @elboy3 for the decoding step in the tokenizer we can avoid this by doing `tokenizer.decoder(..., skip_special_tokens=True)`

2023-08-14 18:19 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
For the decoding this is a great point! 

But when we also are logging / handling the `logits` I think that we will want to strip the `<eos>` token probability. Unless we think that this is actually something we want to surface to the user. Which, I kind of go back and forth on. If their tokenizer is adding it than I may almost be learning more on the side of having us show it. But I think that this could be a bigger discussion that I will post in the ml channel.

2023-08-14 18:20 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
> If we want to drop something, let's use a mask instead of relying on slicing.

For this do you mean using something like `generated_tokens = generated_tokens[np.where(generated_tokens != eos_token_id)[0]]`? Is the idea that a mask is a bit more precise than slicing?

2023-08-14 18:34 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            )
> I don't really follow how the type changes if we use beam search 🤔. From what I remember and ([just confirmed from the docs](https://huggingface.co/docs/transformers/v4.31.0/en/generation_strategies#beamsearch-decoding)) the dtype remains the same: str regardless of beam search (list is because it's a "batch" being decoded), since beam search is an internal decoding detail and not surfaced to the user as multiple responses.

The difference comes from when you want to get back the model logits - i.e. when you pass in `return_dict_in_generate=True` and `output_scores=True`. In this situation the beams are inadvertently surfaced to the user as multiple probabilities vectors (beams) per token. Looking at the [docs here](https://huggingface.co/docs/transformers/v4.30.0/en/main_classes/text_generation#transformers.GenerationMixin.generate) you see that we will get a `Beam[Search/Sampler][EncoderDecoder/DecoderOnly]Output`. While this is certainly something we can handle, it does add complexity on the DQ side for computing probability based metrics, which is why I suggested we maybe add it in V1.

2023-08-14 18:41 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            )
@setu4993 One thing for example with fine-tuning is I don't think that users are always generating at each step in their validation loop. Since in general metrics for generative tasks can be quite weak, I think often people just look at perplexity as a proxy for val performance. However, the flip side is certainly that val perplexity does not always correlate with human rater eval (e.g. discussed in [Lima](https://arxiv.org/pdf/2305.11206.pdf) where they use manual selection of a checkpoint based on a tiny held out set). 

Maybe we can have a bigger discussion about this not over messages. I am not sure I see why their would be mismatch + I think we are ignoring some of the benefits to abstracting away the generation step. In general users face a lot of friction integrating Galileo, and with how standard generation is for LLMs in hf, we get a lot of wins when doing this for the user. As an example, many of the eval libraries take a model and handle the generation for the user.

2023-08-14 20:02 UTC, setu4993 commented on dataquality/utils/seq2seq.py
> +            )
> I am not sure I see why their would be mismatch

Here's a typical LLM finetuning workflow that I've performed for years + seen others do a bunch:
1. Train a model.
2. Perform generation during the validation step with default generation config.
3. Generate during the last validation step with custom generation config.
4. Generate during the test step with custom generation config.

What we're doing here is using the default generation config at step 3, which IMHO would cause a mismatch because we're using the default / Galileo specific config rather than one that the user would use to evaluate their own model.

When I'm generating my final set of generated outputs, you're right, I may not use the final model and a previous checkpoint, which is even more so why I don't think we should generate for the user independent of the generation steps they're using as a part of their existing training scripts.

The generation is opinionated, because it has various configurations that completely change the actual result of the generation, which causes a mismatch between what I'd get if I ran the generation myself on a trained model vs. what I'd see on Galileo.

A good middle ground could be to simply let the users log their generation instead of doing the generation _for them_.

Happy to chat about it sync anytime if it'd help!

2023-08-14 20:49 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +            )
I would agree with that work flow! I think there may be some tradeoffs in whether people do full generation during fine-tuning, but I think that is a small detail.

> What we're doing here is using the default generation config at step 3, which IMHO would cause a mismatch because we're using the default / Galileo specific config rather than one that the user would use to evaluate their own model.

I think that this is maybe where we are just slightly mis-communicating. I am certainly not suggesting that we use a `default Galileo generation config`. This would be something that the user provides to us, to as you say, fully control the final generation step over their `validation` and `test` data. 

I think that a fair question is around generating based on different checkpoints. But again I think there is something to be said about ease of utilizing Galileo + working towards an first working version of DQ. In terms of the first (ease of use), if the user can finish training and super easily be able to log generated output to Galileo that seems like a pretty big win - again we obviously are sacrificing some customizability, but as we have seen tons of users have loved `dq.auto`. On the second (building towards a first working version), this is also certainly the easier first assumption, since otherwise there is much more nuance around getting the users `logits`, etc. 

I definitely think that at some point we should support user logged generations! I just don't know if I agree that it is an early middle ground? It just seems like the other end of the spectrum.

2023-08-14 21:07 UTC, jonathangomesselman commented on dataquality/utils/seq2seq.py
> +                # generated_logits = generation_respone.scores[:-1]
My only thinking here is that if these tokens appear at other indices, it may signal something unexpected. In this case, we may even want to throw some flag or something.

2023-10-04 14:41 UTC, closed without merging

2023-10-04 14:41 UTC, elboy3 commented
We have merged this work in separate PRs, closing!