Support latest Ultralytics version
rungalileo/dataquality pull request #759
Opened 2023-10-02 23:41 UTC by franz101

Support moving from get_settings to SettingsManager and support new imports

2023-10-02 23:52 UTC, setu4993 reviewed
The Ultralyics changes look fine, but there's some overlap with what should have changed in #756.

There also appears to be a mismatch in how we're supporting this since we're pinning to an old version of `ultralytics`.

2023-10-02 23:52 UTC, setu4993 commented on tests/integrations/keras/test_end2end_keras.py
> +    from tensorflow.python.keras.engine import data_adapter  # type: ignore
Isn't this from #756?

2023-10-02 23:52 UTC, setu4993 commented on pyproject.toml
> +    "ultralytics<=8.0.162",
I'm guessing we aren't really supporting the latest Ultralytics version (PR title) since we're pinning it here and the latest is [v8.0.191](https://pypi.org/project/ultralytics/#history)?

2023-10-03 19:49 UTC, elboy3 requested changes
Your exception message shows `"This version of dqyolo is only compatible with ultralytics==8.0.190"` but the pyproejct shows >=8.0.190.... let's be consistent

2023-10-03 19:54 UTC, franz101 commented
> Your exception message shows `"This version of dqyolo is only compatible with ultralytics==8.0.190"` but the pyproejct shows >=8.0.190.... let's be consistent
Changed it to:
"This version of dqyolo is not compatible with ultralytics below 8.0.190."
"Please upgrade ultralytics with `pip install --upgrade ultralytics==8.0.190"
"or higher."

2023-10-03 20:12 UTC, franz101 commented on tests/integrations/keras/test_end2end_keras.py
> +    from tensorflow.python.keras.engine import data_adapter  # type: ignore
removed, was causing the tests not to run as m1 only supports keras 2.13.0

2023-10-03 20:13 UTC, franz101 commented on pyproject.toml
> +    "ultralytics<=8.0.162",
updated

2023-10-03 20:38 UTC, elboy3 approved these changes

2023-10-03 21:07 UTC, merged