fix: model to cpu for cuda cleanup
rungalileo/dataquality pull request #775
Opened 2023-10-16 19:55 UTC by elboy3

https://app.shortcut.com/galileo/story/8227/dq-move-model-to-cpu-before-cleanup

For @dcaustin33

2023-10-16 19:57 UTC, dcaustin33 approved these changes

2023-10-16 19:58 UTC, dcaustin33 commented on dataquality/utils/torch.py
> +            with torch.no_grad():
Dont need no grad here

2023-10-16 22:00 UTC, setu4993 requested changes
Urm, credentials in notebook.

2023-10-17 01:24 UTC, elboy3 commented
> Urm, credentials in notebook.

Eeek! my bad ... squashed in an interactive rebase so it's not in commit history

2023-10-17 01:24 UTC, setu4993 approved these changes

2023-10-17 13:23 UTC, merged