feat: s2s add high dep tokens
rungalileo/dataquality pull request #809
Opened 2023-11-22 21:26 UTC by bogdan-galileo

Goal is to compute high dep tokens https://app.shortcut.com/galileo/story/9232/dq-save-nessec-column-for-high-dep-tokens?vc_group_by=day&ct_workflow=all&cf_workflow=500000005

The DQ work requires saving the target tokens. We later groupby them (and the ID is not enough as we need the tokens for the UI).

Decoding the target token ids is fast enough
![Screenshot 2023-11-22 at 3 48 27 PM](https://github.com/rungalileo/dataquality/assets/112427971/009eedd8-fad0-41ac-8191-190a799b301f)

2023-11-27 17:44 UTC, elboy3 commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +        data_logger.token_label_str = tokenizer.batch_decode(token_label_ids)
so batch decode is on scale of a few seconds? that's nice

2023-11-27 17:44 UTC, elboy3 commented
Have we created any runs in dev minio as a little test?

2023-11-28 15:24 UTC, bogdan-galileo commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +        data_logger.token_label_str = tokenizer.batch_decode(token_label_ids)
Yeah. If it ever start to take longer at some point (larger datasets, decode not as good, etc) we could also extract the token string values using the text + the offsets, it's immediate (~50 times faster).

I just don't like it as much as we'd have to clean up the string from " " and "\n" and probably other things
![Screenshot 2023-11-28 at 10 24 09 AM](https://github.com/rungalileo/dataquality/assets/112427971/9a5311e8-4c83-4900-a514-7cbfc79a886b)

2023-11-28 15:46 UTC, bogdan-galileo commented
> Have we created any runs in dev minio as a little test?

Yeah just tested, looks good. After processing the length of the tokens aligns with the length of tokens deps too 
![Screenshot 2023-11-28 at 10 45 18 AM](https://github.com/rungalileo/dataquality/assets/112427971/5e74b90f-c636-4609-9157-2f0b688a8fe0)

2023-11-28 16:41 UTC, jonathangomesselman requested changes
Looks great! I left some feedback in the `Decoder-Only` section. I think that you may need to move the location of where you do the decoding to properly decode all of the samples.

2023-11-28 16:41 UTC, jonathangomesselman commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +        use_special_tokens = True  # use this var to align encoding and decoding
Why do we create a var here and not just call pass in `True`

2023-11-28 16:41 UTC, jonathangomesselman commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +                clean_up_tokenization_spaces=True,
What does `clean_up_tokenization_spaces` do again? I have seen it but never fully understood it.

2023-11-28 16:41 UTC, jonathangomesselman commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +            data_logger.token_label_str = [
I don't think this is going to work. The result of this will be just saving the de-tokenized tokens for the last sample. For decoder only we loop over each sample individually, since we need to isolate the response template. You probably want to do this outside the loop!

2023-11-29 16:49 UTC, bogdan-galileo commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +        use_special_tokens = True  # use this var to align encoding and decoding
I also use it below in the decoding, so it's to make sure that they align so that the token_ids and token_str have the same lengths

2023-11-29 16:53 UTC, bogdan-galileo commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +                clean_up_tokenization_spaces=True,
Supposedly to remove spaces added during tokenization https://discuss.huggingface.co/t/what-does-the-parameter-clean-up-tokenization-spaces-do-in-the-tokenizer-decode-function/17399. But I've never seen those spaces with the T5 tokenizer, and in the decoder only notebook, the tokenizer adds those spaces at the beginninng of each word, and using True does not remove the spaces!

Still I think it cleans up a bit the token string in some cases.

2023-11-29 16:53 UTC, bogdan-galileo commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +            data_logger.token_label_str = [
Fixed and did a run with decoder only, the data in minio aligns

![Screenshot 2023-11-29 at 11 40 13 AM](https://github.com/rungalileo/dataquality/assets/112427971/aeabdb76-aa15-4f80-805e-c764c57e260e)

2023-11-29 20:14 UTC, jonathangomesselman approved these changes
Looks good to me!

2023-11-29 20:14 UTC, jonathangomesselman commented on dataquality/loggers/data_logger/seq2seq/formatters.py
> +            data_logger.token_label_str.append(
Nice!

2023-11-29 20:16 UTC, merged