feat: Upload model after finishing training
rungalileo/dataquality pull request #826
Opened 2024-01-23 00:09 UTC by franz101

Part of:
https://app.shortcut.com/galileo/story/10988/jpmc-allow-simple-upload-of-csv-to-train-a-model-and-get-dataquality-insights

2024-01-29 05:06 UTC, elboy3 commented on dataquality/utils/auto_trainer.py
> +    dq.finish(wait=wait, create_data_embs=create_data_embs, upload_model=True)
auto is going to always upload model? idk why that feels too aggressive, it should be just when they specify it

2024-01-29 05:06 UTC, elboy3 commented on dataquality/integrations/transformers_trainer.py
> +    helper_data["model_kind"] = "transformers"
can we make a dataclass that includes `transformers` rather than magic str

2024-01-29 05:07 UTC, elboy3 commented on dataquality/clients/api.py
> +        )
to me it's a bit odd that one of these endpoints is `upload_model` and the other `model`, shouldn't they be the same but one is a POST and one is a GET?

2024-01-29 05:08 UTC, elboy3 commented on dataquality/utils/upload_model.py
> +def upload_model_to_dq() -> None:
i think this fn should take in a model 

also you are not upoading the model to dq you are uploading it to object store

2024-01-29 05:10 UTC, elboy3 commented on dataquality/clients/api.py
> +    def get_presigned_url_for_model(
this fn should just return the `presigned_url` based on the fn name

2024-01-29 05:14 UTC, elboy3 requested changes
looking pretty good, but left a few suggestions, also gotta format / lint. Main concern is that I'm not sure all auto flows should upload model by default, would love to discuss that detail

2024-01-30 02:53 UTC, franz101 commented
I agree with auto. We can just make sure the dq.auto on sagemaker always uploads so you can later use it for inference

2024-02-01 16:48 UTC, franz101 commented on dataquality/utils/auto_trainer.py
> +    dq.finish(wait=wait, create_data_embs=create_data_embs, upload_model=True)
Otherwise you could not press the inference button. Let's disable it for now and then in the future, we can enable it.

2024-02-01 17:09 UTC, franz101 commented on dataquality/integrations/transformers_trainer.py
> +    helper_data["model_kind"] = "transformers"
done

2024-02-01 17:10 UTC, franz101 commented on dataquality/clients/api.py
> +        )
changed

2024-02-01 17:16 UTC, franz101 commented on dataquality/utils/upload_model.py
> +def upload_model_to_dq() -> None:
done, model is Any for now since huggingface can have many different model classes

2024-02-01 17:18 UTC, franz101 commented
@elboy3 Sir, please reconsider (I have added all your requests)

2024-02-01 22:04 UTC, elboy3 commented on dataquality/clients/api.py
> +        Will also update the status to complete.
why does it update the status to complete? 

also what does it return, the model or a presigned url to download it?

2024-02-01 22:05 UTC, elboy3 commented on dataquality/core/finish.py
> +            model_kind = helper_data["model_kind"]
you should move these under the if on line 99. if "model" is not in `helper_data` it will have already thrown an error on 96

2024-02-01 22:13 UTC, franz101 commented on dataquality/clients/api.py
> +        Will also update the status to complete.
since we don't know on the backend when a minio upload is completed we update it every time we get the model and if the filename is not saved.

2024-02-02 21:05 UTC, elboy3 commented on pyproject.toml
> -    "pydantic>=2.0.0",
i don't think you need any of these.... i fixed the tests and all the formatting issues earlier today just merge the latest from main and keep the pyproject.toml the same

2024-02-02 21:05 UTC, elboy3 commented on tests/loggers/test_seq2seq.py
> +
don't need this whitespace

2024-02-02 21:05 UTC, elboy3 commented on dataquality/core/finish.py
> +            model_kind = helper_data["model_kind"]
wait, this isn't resolved. Can you move these below the if?

2024-02-02 21:06 UTC, elboy3 commented on dataquality/clients/api.py
> +        Will also update the status to complete.
so what status is it updating, the job status?

2024-02-02 21:26 UTC, franz101 commented on dataquality/clients/api.py
> +        Will also update the status to complete.
just the upload is completed. at first it's the put link, once it's put we will pull the download link from minio and add it to the entry

2024-02-02 21:32 UTC, franz101 commented
Added test and reverted pyproject, ready to merge

2024-02-02 22:36 UTC, elboy3 approved these changes

2024-02-02 22:36 UTC, merged