feat(cu12): Support for cuda12
rungalileo/dataquality pull request #845
Opened 2024-03-18 16:15 UTC by franz101

**Shortcut:**
https://app.shortcut.com/galileo/story/12155/robustify-csv-upload-auto-training
**Description:**
Currently pip install dataquality[cuda] will not work on colab nor our csv upload

Some background colab is running cuda 12 (see screenshot in the comment)

Installing a pycuda 11 will cause an error and not execute running the umap locally

Reproducible examples (make sure to disconnect and delete runtime before testing it):
https://colab.research.google.com/drive/1_ExNBwu80aOriIO8YO1UDYsOREhRzbdO?usp=sharing

2024-03-18 17:16 UTC, setu4993 commented on pyproject.toml
> +accelerate = "==0.27.2"
Why pin this?

2024-03-18 17:16 UTC, setu4993 reviewed
Can you add a bit more context about why this change?

2024-03-18 17:16 UTC, setu4993 commented on dataquality/clients/objectstore.py
> +            endpoint=str(config.minio_fqdn),
Curious about the change here?

2024-03-18 17:59 UTC, elboy3 commented on dataquality/utils/patcher.py
> +            pass
What would cause the TypeError and why do we want to do nothing on it

2024-03-18 18:41 UTC, franz101 commented
Some background colab is running coda 12

![Screenshot 2024-03-18 at 19 41 03](https://github.com/rungalileo/dataquality/assets/18228395/d37615ca-0c5f-4ab7-9e85-8aab432550e2)


Installing a pycuda 11 will cause an error and not execute running the umap locally

https://colab.research.google.com/drive/1_ExNBwu80aOriIO8YO1UDYsOREhRzbdO?usp=sharing

2024-03-18 18:42 UTC, franz101 commented on dataquality/utils/patcher.py
> +            pass
The reference is already garbage collected and then this would call the function even though it does not exist anymore, I can look into this but this would cause the program to crash at the end after training is complete (training / upload is not affected)

2024-03-18 18:43 UTC, franz101 commented on dataquality/clients/objectstore.py
> +            endpoint=str(config.minio_fqdn),
mypy was giving me an error so changed this for precommit

2024-03-18 18:51 UTC, franz101 commented on pyproject.toml
> +accelerate = "==0.27.2"
https://github.com/huggingface/transformers/issues/29216

2024-03-18 18:59 UTC, franz101 commented
> Can you add a bit more context about why this change?

So a customer upload 114k samples which took hours to process the umap on our server.
I noticed A: Cuda is broken on colab
I noticed B: Changing to a cuda runtime in the sagemaker container caused two minor bugs / accelerate + garbage collection.

I have tested this fixed version on colab and sagemaker

2024-03-18 20:00 UTC, setu4993 commented
But what about customers that still use Cuda 11?

2024-03-18 20:56 UTC, franz101 commented
> But what about customers that still use Cuda 11?

Then we need to split it in dataquality[cu11]

Can't support both afaik

2024-03-19 00:54 UTC, setu4993 commented on dataquality/clients/objectstore.py
> +            endpoint=str(config.minio_fqdn),
What I was trying to get at is: What changed _now_ that is causing it to fail?

Anyway.

2024-03-19 00:54 UTC, setu4993 commented on pyproject.toml
> +sentencepiece = "^0.2.0"
Should this be optional?

2024-03-20 23:19 UTC, franz101 commented on pyproject.toml
> +sentencepiece = "^0.2.0"
Not sure, was like this before

2024-03-20 23:20 UTC, franz101 commented on pyproject.toml
> +sentencepiece = "^0.2.0"
I assume by the position

2024-03-20 23:27 UTC, franz101 commented
@setu4993 any idea on how to fix the poetry part?
I was not able to make it work having them not installed or resolved together:
specifically it causes:
```
Because no versions of cuml-cu11 match >24.2.0,<25.0.0
 and cuml-cu11 (24.2.0) depends on pylibraft-cu11 (==24.2.*), cuml-cu11 (>=24.2.0,<25.0.0) requires pylibraft-cu11 (==24.2.*).
And because no versions of pylibraft-cu11 match >24.2.0,<24.3.dev0
 and pylibraft-cu11 (24.2.0) depends on cuda-python (>=11.7.1,<12.0a0), cuml-cu11 (>=24.2.0,<25.0.0) requires cuda-python (>=11.7.1,<12.0a0) or pylibraft-cu11 (>=24.2.dev0,<24.2.0).
Because pylibraft-cu12 (24.2.0) depends on cuda-python (>=12.0,<13.0a0)
 and no versions of pylibraft-cu12 match >24.2.0,<24.3.dev0, pylibraft-cu12 (>=24.2.0,<24.3.dev0) requires cuda-python (>=12.0,<13.0a0).
Thus, if cuml-cu11 (>=24.2.0,<25.0.0) and pylibraft-cu12 (>=24.2.0,<24.3.dev0) then pylibraft-cu11 (>=24.2.dev0,<24.2.0).
And because cuml-cu12 (24.2.0) depends on pylibraft-cu12 (==24.2.*)
 and no versions of cuml-cu12 match >24.2.0,<25.0.0, if cuml-cu11 (>=24.2.0,<25.0.0) and cuml-cu12 (>=24.2.0,<25.0.0) then pylibraft-cu11 (>=24.2.dev0,<24.2.0) or pylibraft-cu12 (>=24.2.dev0,<24.2.0).
And because dataquality depends on both pylibraft-cu12 (^24.2.0) and cuml-cu12 (^24.2.0), cuml-cu11 (>=24.2.0,<25.0.0) requires pylibraft-cu11 (>=24.2.dev0,<24.2.0).
So, because dataquality depends on both pylibraft-cu11 (^24.2.0) and cuml-cu11 (^24.2.0), version solving failed.
```


```
[project.optional-dependencies]
cuda = ["ucx-py-cu11", "rmm-cu11", "raft-dask-cu11", "pylibraft-cu11", "dask-cudf-cu11", "cudf-cu11", "cuml-cu11"]
cuda12 = ["ucx-py-cu12", "rmm-cu12", "raft-dask-cu12", "pylibraft-cu12", "dask-cudf-cu12", "cudf-cu12", "cuml-cu12"]
```

2024-03-20 23:31 UTC, setu4993 commented on pyproject.toml
> +accelerate = "==0.27.2"
It looks like it's working with any of the latest versions? https://github.com/huggingface/transformers/issues/29216#issuecomment-2009050327

2024-03-20 23:34 UTC, setu4993 commented
We could use [dependency groups](https://python-poetry.org/docs/managing-dependencies/#optional-groups).

2024-04-04 12:55 UTC, franz101 commented
I have added a not so pretty replacement to unblock this ticket.

2024-04-04 19:16 UTC, elboy3 requested changes
My suggestion is to support cuda12 but have instructions for how a customer can run this if they are using cuda 11 in our docs

2024-04-04 22:18 UTC, franz101 commented
reverted to pip install dataquality[cuda12]

2024-04-16 21:08 UTC, closed without merging